apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels: { app: guestbook }
  template:
    metadata: { labels: { app: guestbook } }
    spec:
      containers:
      - name: guestbook
        image: shreyas24150/guestbook:v1
        ports: [{ containerPort: 80 }]
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  type: NodePort
  selector: { app: guestbook }
  ports: [{ port: 80, targetPort: 80 }]
