name: Build and Deploy via GitOps

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - ".github/workflows/**"

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: shreyas24150/guestbook
      DEPLOYMENT_FILE: apps/guestbook/base/deployment.yaml

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          TAG=v${{ github.run_number }}
          docker build -t $IMAGE_NAME:$TAG app/
          docker push $IMAGE_NAME:$TAG
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s#image: .*\$#image: $IMAGE_NAME:${{ env.IMAGE_TAG }}#" $DEPLOYMENT_FILE

      - name: Commit and push manifest change
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add $DEPLOYMENT_FILE
          git commit -m "Update image to $IMAGE_NAME:${{ env.IMAGE_TAG }}"
          git push
